spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_center
    hikari:
      username: root
      password: root
      # >+ 6.X  com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update  # \u7B2C\u4E00\u6B21\u5EFA\u8868create  \u540E\u9762\u7528update\uFF0C\u8981\u4E0D\u7136\u6BCF\u6B21\u91CD\u542F\u90FD\u4F1A\u65B0\u5EFA\u8868
    show-sql: true
  cloud:
    nacos:
      discovery:
        # \u6307\u5B9Anacos server\u5730\u5740
        server-addr: localhost:8848
        cluster-name: BeiJing
        metadata:
          param1: haha
          version: 1.0.1

  application:
    name: user-center

logging:
  level:
    root: INFO
    # \u914D\u7F6E\u65E5\u5FD7\u7EA7\u522B\uFF0C\u8BA9hibernate\u6253\u5370\u51FA\u6267\u884C\u7684SQL\u53C2\u6570
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
server:
  port: 8010