spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/content_center
    hikari:
      username: root
      password: root
      # >+ 6.X  com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
#解决feignClient 重复实例名字bean无法启动的问题
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        # \u6307\u5B9Anacos server\u5730\u5740
        server-addr: localhost:8848
        cluster-name: BeiJing
  application:
    name: content-center
server:
  port: 8011

#自定义细粒度配置负载均衡策略->配置文件方式  只需在调用方配置被调用方的策略
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 懒加载配置  解决第一次请求过慢问题
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
#feign 细粒度配置
#feign:
#  client:
#    config:
#      # 想要调用的微服务的名称
#      user-center:
#        loggerLevel: full
feign:
  client:
    config:
      # 想要调用的微服务的名称
      default:
        loggerLevel: full
  httpclient:
    #让feign使用apache httpclient作请求，而不是默认的urlconnecton
    enabled: true
    # feign最大连接数
    max-connections: 200
    #单个路径的最大连接数
    max-connections-per-route: 50

#开启acturator所有端点
management:
  endpoints:
    web:
      exposure:
        incloud: '*'