spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/content_center?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    hikari:
      username: root
      password: root
      # >+ 6.X  com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://127.0.0.1:9411/
    #    discoveryClientEnabled: false
  sleuth:
    sampler:
      #抽样率(默认0.1)
      probability: 1.0
#解决feignClient 重复实例名字bean无法启动的问题
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        # \u6307\u5B9Anacos server\u5730\u5740
        server-addr: localhost:8848
        cluster-name: BeiJing
    sentinel:
      filter:
        # 打开/关闭对springmvc 端点的保护  打开会导致 sentinel控制台看不到微服务的端点
        enabled: true
      transport:
        #指定sentinel 控制台的地址
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: wx-add-bonus-group

      bindings:
        output:
          #测试
          #destination: stream-test-topic
          destination: add-bonus


server:
  port: 8011

#自定义细粒度配置负载均衡策略->配置文件方式  只需在调用方配置被调用方的策略
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 懒加载配置  解决第一次请求过慢问题
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error
#feign 细粒度配置
#feign:
#  client:
#    config:
#      # 想要调用的微服务的名称
#      user-center:
#        loggerLevel: full
feign:
  sentinel:
    # 为feign整合setinel
    enabled : true
  client:
    config:
      # 想要调用的微服务的名称
      default:
        loggerLevel: full
        requestinterceptors:
          - com.itmuch.contentcenter.interceptor.TokenRelayRequestInterceptor
  httpclient:
    #让feign使用apache httpclient作请求，而不是默认的urlconnecton
    enabled: true
    # feign最大连接数
    max-connections: 200
    #单个路径的最大连接数
    max-connections-per-route: 50

#开启acturator所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#ahas:
#  namespace: default
#  license: 0f9ee689413445088be1967f5b00c1b4
#project:
#  name: content-center

## stream整合rocketmq
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    #小坑 必须指定group
#    group: test-group

jwt:
  secret: 2333hahahahahahha
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600